include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: ["**/*.mocks.dart", "**/generated_plugin_registrant.dart", "**/*.g.dart", "**/*.gr.dart", "**/*.config.dart"]
linter:
  rules:
    depend_on_referenced_packages: false
