name: flutter_architecture
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  # router
  auto_route: ^4.0.1
  # Dependency Injection
  get_it: ^7.2.0
  injectable: ^1.5.3
  # converters
  copy_with_extension: ^4.0.2
  json_serializable: ^6.2.0
  # Http requisite
  dio: ^4.0.6
  # client HTTP
  retrofit: ">=3.0.1+1"
  logger: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  auto_route_generator: ^4.0.0
  copy_with_extension_gen: ^4.0.2
  injectable_generator: ^1.5.3
  effective_dart: ^1.3.2
  retrofit_generator: ">=4.0.1"

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner

scripts:
  g: $clean & $get & $runner --delete-conflicting-outputs
  gw: $clean & $get & $runner watch --delete-conflicting-outputs
  cg: $clean & $get
